# Generated by Django 5.2.1 on 2025-07-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='company_name',
            field=models.CharField(default='Vogona', max_length=100),
        ),
    ]
