# Generated by Django 5.2.1 on 2025-08-04 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='phonenumber',
            new_name='phone_number',
        ),
    ]
