# Generated by Django 5.2.1 on 2025-12-11 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_payment_order_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_totle',
            new_name='order_total',
        ),
    ]
